In [1]:
import cv2 as cv
import numpy as np
import math
import sys
import matplotlib.pyplot as plt

In [2]:
def load_image():
    # image load
    img = cv.imread("../../Data/graffiti.png")

    # convert to RGB
    img = cv.cvtColor(img, cv.COLOR_BGR2RGB)

    return img

In [19]:
# Load the image
img = load_image()

# reshape the image to a 2D array of pixels and 3 color values (RGB)
pixel_values = img.reshape((-1, 3))

# convert to float
pixel_values = np.float32(pixel_values)

In [20]:
pixel_values.shape

(512000, 3)

In [21]:
dist_mat = np.zeros([pixel_values.shape[0], pixel_values.shape[0]])

In [74]:
def calculate_dist(a, b):
    
    dist = np.square(a - b) #+ np.square(b)
    
    square_eu_dist = np.sum(dist, axis=1)
    
    return np.sqrt(square_eu_dist)

In [75]:
for i in range(pixel_values.shape[0]):
    
    if i == 1:
        break
    
    X1_tmp = pixel_values[i, :]
    X = np.repeat([X1_tmp], pixel_values.shape[0], axis=0) 
    Y = pixel_values[:, :]
    
    dist = calculate_dist(X, Y)
    
    print(X.shape, Y.shape)
    
    print(dist.shape)

(512000, 3) (512000, 3)
(512000,)


In [76]:
pixel_values[0:10, :]

array([[219., 209., 215.],
       [216., 206., 215.],
       [206., 196., 207.],
       [187., 178., 191.],
       [174., 166., 180.],
       [161., 154., 166.],
       [156., 150., 159.],
       [155., 149., 159.],
       [156., 149., 161.],
       [156., 151., 162.]], dtype=float32)

In [77]:
dist[0:10]

array([  0.       ,   4.2426405,  20.049938 ,  50.606323 ,  71.40728  ,
        93.755    , 102.88829  , 104.0769   , 102.396286 , 100.7075   ],
      dtype=float32)

In [79]:
v1 = np.square(pixel_values[0, :] - pixel_values[1, :])

print(v1)

[9. 9. 0.]


In [ ]:
|